<?php

use Livewire\Volt\Component;
use Livewire\Attributes\Layout;
use Livewire\Attributes\Title;

new 
#[Layout('livewire.layout.component')] 
#[Title('PIN Code — Aura Wire')] 
class extends Component {};

?>

<x-aura::container gap="8" :padding="false">

    <!-- Header -->
    <x-aura::card size="full" gap="2">

        <x-aura::flex align="center" gap="2.5">

            <x-aura::kicker>
                Form
            </x-aura::kicker>

            <x-aura::badge variant="subtle" size="md">
                Component
            </x-aura::badge>

        </x-aura::flex>

        <x-aura::heading level="1" size="xl">
            PIN Code
        </x-aura::heading>

        <x-aura::subheading size="md">
            Multi digit OTP and security verification PIN inputs with auto focus movement.
        </x-aura::subheading>

    </x-aura::card>

    <!-- Component Syntax -->
    <x-aura::code variant="dark" title="Component Syntax" :showTabs="false" active="code">

        <x-slot:codeSlot>

            @verbatim
                <x-aura::pin-code length="4" size="md" />
            @endverbatim

        </x-slot:codeSlot>

    </x-aura::code>

    <!-- 1. 4-Digit PIN Code -->
    <x-aura::code title="1. 4 Digit Passcode">

        <x-slot:preview>

            <x-aura::card size="2xl" gap="4">

                <x-aura::flex direction="col" align="start" gap="2">

                    <x-aura::label>
                        Enter 4 Digit Passcode
                    </x-aura::label>

                    <x-aura::pin-code length="4" size="md" />

                </x-aura::flex>

            </x-aura::card>

        </x-slot:preview>

        <x-slot:codeSlot>

            @verbatim
                <x-aura::flex direction="col" align="start" gap="2">
                    <x-aura::label>
                        Enter 4 Digit Passcode
                    </x-aura::label>

                    <x-aura::pin-code length="4" size="md" />
                </x-aura::flex>
            @endverbatim

        </x-slot:codeSlot>

    </x-aura::code>

    <!-- 2. 6-Digit 2FA Verification Card -->
    <x-aura::code title="2. 6 Digit Two Factor Verification (length=6 size=lg)">

        <x-slot:preview>

            <x-aura::card size="2xl" padding="xl" gap="6">

                <x-aura::flex direction="col" align="center" gap="4" class="text-center">

                    <x-aura::heading level="3" size="lg">
                        Two Step Verification
                    </x-aura::heading>

                    <x-aura::text size="sm" variant="subtle">
                        Please enter the 6 digit code generated by your authenticator app.
                    </x-aura::text>

                    <x-aura::pin-code length="6" size="lg" />

                    <x-aura::button variant="primary" size="md">
                        Verify
                    </x-aura::button>

                </x-aura::flex>

            </x-aura::card>

        </x-slot:preview>

        <x-slot:codeSlot>

            @verbatim
                <x-aura::card size="2xl" padding="xl" gap="6">
                    <x-aura::flex direction="col" align="center" gap="4" class="text-center">
                        <x-aura::heading level="3" size="lg">
                            Two Step Verification
                        </x-aura::heading>

                        <x-aura::text size="sm" variant="subtle">
                            Please enter the 6 digit code generated by your authenticator app.
                        </x-aura::text>

                        <x-aura::pin-code length="6" size="lg" />

                        <x-aura::button variant="primary" size="md">
                            Verify
                        </x-aura::button>
                    </x-aura::flex>
                </x-aura::card>
            @endverbatim

        </x-slot:codeSlot>

    </x-aura::code>

    <!-- 3. Size Variations -->
    <x-aura::code title="3. Size Variations">

        <x-slot:preview>

            <x-aura::card size="2xl" gap="4">

                <x-aura::flex direction="col" gap="4">

                    <x-aura::flex direction="col" gap="1">
                        <x-aura::text size="xs" variant="subtle">Small (size=sm):</x-aura::text>
                        <x-aura::pin-code length="4" size="sm" />
                    </x-aura::flex>

                    <x-aura::flex direction="col" gap="1">
                        <x-aura::text size="xs" variant="subtle">Medium (size=md):</x-aura::text>
                        <x-aura::pin-code length="4" size="md" />
                    </x-aura::flex>

                    <x-aura::flex direction="col" gap="1">
                        <x-aura::text size="xs" variant="subtle">Large (size=lg):</x-aura::text>
                        <x-aura::pin-code length="4" size="lg" />
                    </x-aura::flex>

                </x-aura::flex>

            </x-aura::card>

        </x-slot:preview>

        <x-slot:codeSlot>

            @verbatim
                <x-aura::pin-code length="4" size="sm" />
                <x-aura::pin-code length="4" size="md" />
                <x-aura::pin-code length="4" size="lg" />
            @endverbatim

        </x-slot:codeSlot>

    </x-aura::code>

    <!-- Component Props -->
    <x-aura::card size="full" gap="4">

        <x-aura::flex direction="col" gap="1">

            <x-aura::heading level="2" size="md">
                Component Props
            </x-aura::heading>

            <x-aura::text variant="subtle" size="sm">
                Available properties and configurations for the PIN code component.
            </x-aura::text>

        </x-aura::flex>

        <x-aura::table>

            <x-slot:header>

                <x-aura::table.column>
                    Prop
                </x-aura::table.column>

                <x-aura::table.column>
                    Default
                </x-aura::table.column>

                <x-aura::table.column>
                    Available Values
                </x-aura::table.column>

            </x-slot:header>

            <x-aura::table.row>

                <x-aura::table.cell>

                    <x-aura::flex align="center" gap="1.5" :inline="true">

                        <x-aura::text variant="mono" size="sm" weight="semibold">
                            length
                        </x-aura::text>

                        <x-aura::tooltip text="Total number of discrete PIN digit boxes" position="top">

                            <x-aura::icon name="info" size="xs" />

                        </x-aura::tooltip>

                    </x-aura::flex>

                </x-aura::table.cell>

                <x-aura::table.cell>
                    <x-aura::badge variant="neutral" size="md">
                        4
                    </x-aura::badge>
                </x-aura::table.cell>

                <x-aura::table.cell>
                    <x-aura::text size="sm" variant="subtle">
                        Positive integer (e.g. 4, 6)
                    </x-aura::text>
                </x-aura::table.cell>

            </x-aura::table.row>

            <x-aura::table.row>

                <x-aura::table.cell>

                    <x-aura::flex align="center" gap="1.5" :inline="true">

                        <x-aura::text variant="mono" size="sm" weight="semibold">
                            size
                        </x-aura::text>

                        <x-aura::tooltip text="Width and height dimensions for each digit box" position="top">

                            <x-aura::icon name="info" size="xs" />

                        </x-aura::tooltip>

                    </x-aura::flex>

                </x-aura::table.cell>

                <x-aura::table.cell>
                    <x-aura::badge variant="neutral" size="md">
                        md
                    </x-aura::badge>
                </x-aura::table.cell>

                <x-aura::table.cell>

                    <x-aura::flex align="center" gap="1.5" :wrap="true">

                        <x-aura::badge variant="subtle" size="md">
                            sm
                        </x-aura::badge>

                        <x-aura::badge variant="subtle" size="md">
                            md
                        </x-aura::badge>

                        <x-aura::badge variant="subtle" size="md">
                            lg
                        </x-aura::badge>

                    </x-aura::flex>

                </x-aura::table.cell>

            </x-aura::table.row>

        </x-aura::table>

    </x-aura::card>

</x-aura::container>
